name: Deploy DiaryAPI to Gigalixir

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unshallow git origin
        run: git fetch --unshallow origin

      - name: Setup Python # Gigalixir is written in python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Gigalixir
        run: |
          sudo pip3 install gigalixir --ignore-installed six

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.1"
          otp-version: "26"

      - name: Install Dependencies
        run: mix deps.get

      - name: Deploy to Gigalixir
        run: |
          gigalixir login -e "${{ secrets.GIGALIXIR_USERNAME }}" -y -p "${{ secrets.GIGALIXIR_PASSWORD }}"
          gigalixir git:remote diary-api
          git push -f gigalixir HEAD:refs/heads/main --force

      - name: Run Migrations
        env:
          MIX_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          gigalixir run mix ecto.migrate
