name: Deploy DiaryAPI to Gigalixir

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.1"
          otp-version: "26"

      - name: Install Dependencies
        run: |
          mix deps.get

      - name: Deploy to Gigalixir
        uses: mhanberg/gigalixir-action@v0.6.1
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GIGALIXIR_APP: diary-api
          MIGRATIONS: true

      - name: Run Migrations
        env:
          MIX_ENV: prod
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        run: |
          gigalixir run mix ecto.migrate
